# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('chromosome', models.CharField(max_length=16)),
                ('position', models.IntegerField()),
                ('genome_release', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=16)),
                ('latitude', models.FloatField()),
                ('longititude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('geo_source', models.CharField(max_length=256)),
                ('geo_datum', models.CharField(max_length=32)),
                ('geo_resolution', models.IntegerField()),
                ('geo_values', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('abbreviation', models.CharField(max_length=16)),
                ('crop_ontology_id', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=256)),
                ('scale', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('seed_source', models.CharField(max_length=45)),
                ('generation', models.CharField(max_length=16)),
                ('previous_testing', models.CharField(max_length=45)),
                ('unique_traits', models.CharField(max_length=45)),
                ('maternal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maternal', to='urt.Strain')),
                ('paternal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paternal', to='urt.Strain')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Test_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_spacing', models.IntegerField()),
                ('rows_per_plot', models.IntegerField()),
                ('yield_cv', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yield_lsd', models.DecimalField(decimal_places=2, max_digits=5)),
                ('note', models.CharField(max_length=256)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urt.Location')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urt.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urt.Strain')),
                ('test_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urt.Test_location')),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='phenotype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urt.Phenotype'),
        ),
        migrations.AddField(
            model_name='observation',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urt.Trial'),
        ),
        migrations.AddField(
            model_name='genotype',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urt.Strain'),
        ),
    ]
