# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='maternal_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='strain',
            name='paternal_id',
            field=models.IntegerField(),
        ),
    ]
