# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urt', '0002_auto_20160326_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='generation',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='maternal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='paternal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='previous_testing',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='seed_source',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='unique_traits',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
