# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urt', '0003_auto_20160326_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genotype',
            name='genome_release',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='genotype',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='geo_datum',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='geo_resolution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='geo_source',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='geo_values',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longititude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='crop_ontology_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='scale',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='test_location',
            name='note',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='test_location',
            name='row_spacing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test_location',
            name='rows_per_plot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test_location',
            name='yield_cv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='test_location',
            name='yield_lsd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
