# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urt', '0005_auto_20160326_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='alias_experiment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='alias_pi',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
